# Generated by Django 4.1.3 on 2023-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_geolocation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geolocation",
            name="user",
            field=models.FloatField(null=True),
        ),
    ]
