# Generated by Django 4.1.3 on 2023-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_geolocation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geolocation",
            name="user",
            field=models.IntegerField(null=True),
        ),
    ]
