# Generated by Django 4.1.3 on 2023-03-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_is_driver_user_license_no_user_user_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vechile_image',
        ),
    ]
