# Generated by Django 4.1.7 on 2023-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_user_image_remove_user_vechile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vechile_no',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
