# Generated by Django 4.1.7 on 2023-03-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_busstoploc_remove_user_is_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vechile_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
